# SPDX-License-Identifier: Apache-2.0
# Copyright 2024 Intel Corporation

name: Test integration
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          go build -o build/_output/onos ./cmd/onos
          go build -o build/_output/onos-cli-docs-gen ./cmd/onos-cli-docs-gen
          go build -o build/_output/gnmi_cli ./cmd/gnmi_cli

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: mod lint
        run: |
          go mod tidy
          go mod vendor
          bash -c "diff -u <(echo -n) <(git diff go.sum)"

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54      
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Unit tests
        run: |
          go test github.com/onosproject/onos-cli/pkg/...
          go test github.com/onosproject/onos-cli/cmd/...

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: |
          go mod vendor
          docker build . -f build/onos/Dockerfile \
                  -t onosproject/onos-cli:latest
          rm -rf vendor
  license-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: reuse lint
        uses: fsfe/reuse-action@v2

  fossa-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: FOSSA scan
        uses: fossa-contrib/fossa-action@v3
        with:
          fossa-api-key: 9dc8fa92e3dd565687317beb87b56d89
