# SPDX-License-Identifier: Apache-2.0
# Copyright 2023 Intel Corporation

name: Test integration
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: make build
  
  mod-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: mod update
        run: make mod-update
  
  mod-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: mod lint
        run: make mod-lint

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
      - name: Unit tests
        run: |
          go test github.com/onosproject/onos-cli/pkg/...
          go test github.com/onosproject/onos-cli/cmd/...

  Jenkins-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
      - name: Jenkins tests
        run: |
          export GOPATH="$HOME/go/"
          export PATH=$PATH:$GOPATH/bin
          go install github.com/golang/mock/mockgen@v1.6.0
          go install github.com/jstemmer/go-junit-report@latest
          go install github.com/boumenot/gocover-cobertura@latest
          make jenkins-test

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: |
          docker images
          make onos-cli-docker
      - name: Cleanup Docker images
        run: |
          docker image prune -f
          docker images
