# SPDX-License-Identifier: Apache-2.0
# Copyright 2023 Canonical Ltd.

name: Test integration
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: make build
  
  mod-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: mod update
        run: make mod-update
  
  mod-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: mod lint
        run: make mod-lint

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
      - name: Unit tests
        run: make test

  Jenkins-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
      - name: Jenkins tests
        run: |
          go get github.com/jstemmer/go-junit-report
          make jenkins-test

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: make onos-cli-docker
