name: Test integration
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: make build
  
  mod-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: mod update
        run: make mod-update
  
  mod-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: mod lint
        run: make mod-lint

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Unit tests
        run: make test

  Jenkins-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Jenkins tests
        run: |
          which bash 
          golangci-lint --version | grep 1.52.2 || curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b `go env GOPATH`/bin v1.52.2
          

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: make onos-cli-docker
