name: Test integration
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: test-automation
        run: |
    	  make build
    	  make mod-update
    	  make mod-lint
          make test
	  make jenkins-test
    
	  
